repos:
- repo: local
  hooks:
    - id: jupyter-widget-state
      name: Add widget state to Jupyter notebooks
      description: Ensures Jupyter notebooks have widget state for GitHub rendering
      entry: .github/hooks/add-jupyter-widgets.sh
      language: script
      files: \.ipynb$
      stages: [pre-commit]