services:
  notebooks:
    image: mcr.microsoft.com/devcontainers/python:1-3.13-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:mongodb
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongodb/mongodb-atlas-local:8.0.18
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=library
    ports:
      - 27017:27017

volumes:
  mongodb-data: